version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: listen --api-key ${STRIPE_PRIVATE_KEY} --forward-to web:3000/api/webhooks
